services:
  front:
    image: registry.gitlab.com/pjb_01_g1/kindergarten-suggestion-system/kss_front:latest # Chỉ định Docker image lấy từ GitLab Container Registry
    build: # Nếu image chưa tồn tại, Docker sẽ tự build từ source
      context: ./front # Chỉ định thư mục front trong thư mục root là nơi chứ Dockerfile
      dockerfile: Dockerfile # Sử dụng Dockerfile trong thư mục front
    ports:
      - "80:3000" # Chạy Next.js trên port 3000
    environment:
      - NODE_ENV=production
    restart: unless-stopped # Nếu container bị lỗi thì tự động restart
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  back:
    build: ./back
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - redis
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge