spring:
  datasource:
    url: jdbc:mysql://localhost:3308/KSS
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 10000ms
      lettuce:
        pool:
          max-active: 10
          max-wait: 5000ms
          max-idle: 8
          min-idle: 2
