spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        default_batch_fetch_size: 20
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 60000
      connection-timeout: 10000
      validation-timeout: 3000
      max-lifetime: 300000
      connection-test-query: SELECT 1
      leak-detection-threshold: 10000
  mail:
    host: smtp.gmail.com
    port: 587
    username: kienduccml@gmail.com
    password: pdqmspuihpebobhu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .html
    charset: UTF-8
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 55MB
logging:
  level:
    org.springframework.transaction.interceptor: TRACE
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG

error:
  handling:
    search-super-class-hierarchy: true

springdoc:
  api-docs:
    path: /v3/api-doc
  swagger-ui:
    path: /swagger-ui
application-description: '@project.description@'
application-version: '@project.version@'
access-token-exp: 600000
refresh-token-exp: 60000000
csrf-token-exp: 600000
forgot-password-token-exp: 300000
reset-password-link-header: 'http://localhost:3000/forgot-password/reset-password'
school-detailed-link: 'http://localhost:3000/public/school-owner'
school-detail-link-admin: 'http://localhost:3000/admin/management/school/school-detail/'




