spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000
error:
  handling:
    search-super-class-hierarchy: true

springdoc:
  api-docs:
    path: /v3/api-doc
  swagger-ui:
    path: /swagger-ui
application-description: '@project.description@'
application-version: '@project.version@'
access-token-exp: 600000
refresh-token-exp: 6000000
csrf-token-exp: 600000